export const SET_CURRENT_POSITION = "SET_CURRENT_POSITION";
export const SET_WEATHER_DATE = "SET_WEATHER_DATE";
export const START_LOADING = "START_LOADING";
export const SUCCESS_LOADING = "SUCCESS_LOADING";
export const ERROR_LOADING = "ERROR_LOADING";
export const SET_FORECAST = "SET_FORECAST";
